services:
  api:
    build: .
    container_name: sum-api
    ports:
      - "5003:5003"
    environment:
      PORT: 5003
      JWT_SECRET: ${JWT_SECRET}
      MONGO_URI: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:27017/sum-api?authSource=admin
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules

  mongodb:
    image: mongo:7
    container_name: express-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: sum-api
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
